
import * as Message from './common/Message';

const INIT_AFTERPAYOLD_START = 'INIT_AFTERPAYOLD_START';
const INIT_AFTERPAYOLD_SUCCESS = 'INIT_AFTERPAYOLD_SUCCESS';
export const INIT_AFTERPAYOLD_FAIL = 'INIT_AFTERPAYOLD_FAIL';
export const ADD_LIKE = 'ADD_LIKE';

module.exports = {...Message,...{INIT_AFTERPAYOLD_START,INIT_AFTERPAYOLD_SUCCESS,INIT_AFTERPAYOLD_FAIL,ADD_LIKE}}