import * as Cart from './common/Cart';
import * as Message from './common/Message';

const INIT_SHOPPING_CART_START = 'INIT_SHOPPING_CART_START';
const INIT_SHOPPING_CART_SUCCESS = 'INIT_SHOPPING_CART_SUCCESS';
const INIT_SHOPPING_CART_FALE = 'INIT_SHOPPING_CART_FALE';
const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
const DECREMENT_ITEM_SUCCESS = 'DECREMENT_ITEM_SUCCESS';
const INCREMENT_ITEM_SUCCESS = 'INCREMENT_ITEM_SUCCESS';
const SET_METION_MESSAGE = 'SET_METION_MESSAGE';
const SHOPPINT_CART_TOGGLE_SHOP = 'SHOPPINT_CART_TOGGLE_SHOP';
const SHOPPINT_CART_CHANGE_SHOP_STATE = 'SHOPPINT_CART_CHANGE_SHOP_STATE';
const SUBMIT_SHOPPING_CART_SUCCESS = 'SUBMIT_SHOPPING_CART_SUCCESS';
const SUBMIT_SHOPPING_CART_FAIL = 'SUBMIT_SHOPPING_CART_FAIL';
const ShoppingCartActionTypes = {INIT_SHOPPING_CART_START,INIT_SHOPPING_CART_SUCCESS,INIT_SHOPPING_CART_FALE,DELETE_ITEM_SUCCESS,DECREMENT_ITEM_SUCCESS,INCREMENT_ITEM_SUCCESS,SET_METION_MESSAGE,SHOPPINT_CART_TOGGLE_SHOP,SHOPPINT_CART_CHANGE_SHOP_STATE,SUBMIT_SHOPPING_CART_SUCCESS,SUBMIT_SHOPPING_CART_FAIL};
module.exports = {...Cart,...Message,...ShoppingCartActionTypes};